### ISSUE TITLE
Use merchant primary domains instead of myshopify.com host

### ISSUE THREAD

**Issue by colinbendell** [igrigorik/shopify-core-web-vitals#6]
Currently the `HomeController` (and `CompetitorControllers`) use the `@current_shopify_session.domain` to assume the primary host for a shop. When logged into the admin backoffice it will always be `shoesbycolin.myshopify.com`. However, the majority of our merchants will have their own branded host in `Domains` such as `shoesbycolin.com`. The controllers should use the active domain(s) to query the crux dataset for more accurate results.

**Comment by igrigorik** [comment]
That... makes a lot of sense. Thanks for reporting this! In theory, should be fixed and live. Could you confirm?

**Comment by colinbendell** [comment]
confirmed. looks good
![image](https://user-images.githubusercontent.com/1622597/91461019-838b5700-e856-11ea-834f-4c61b2058f22.png)

**Comment by igrigorik** [comment]
👍 thanks again for flagging this.
